[mysql]
db_username = 'admintable'
db_password = 'table$123'
db_host = 'tableextraction.mysql.database.azure.com'
db_port = '3306'
db_name = 'isb_demo'
#client_flags = '[mysql.connector.ClientFlag.SSL]'
client_flags = 65536
#ssl_ca = 'DigiCertGlobalRootG2.crt.pem'



